version: '3.4'

services:
  docker.multiapp.api:
    image: ${DOCKER_REGISTRY-}dockermultiappapi
    build:
      context: .
      dockerfile: Docker.MultiApp.API/Dockerfile
    depends_on:
      - dockermultiappdb
  docker.multiapp.web:
    image: ${DOCKER_REGISTRY-}dockermultiappweb
    build:
      context: .
      dockerfile: Docker.MultiApp.Web/Dockerfile
    ports:
      - "9000:443"
      - "9001:80"
    depends_on:
      - docker.multiapp.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=9000
  dockermultiappdb:
    image: mcr.microsoft.com/mssql/server:2017-CU17-ubuntu   
    build:      
      context: ./Docker.MultiApp.API/Database 
    environment:
            SA_PASSWORD: "Database!2021"
            ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"